### ISSUE TITLE
Error trying to parse zshmarks.plugin.zsh

### ISSUE THREAD

**Issue by fernandofleury** [jocelynmallon/zshmarks#19] opened 2015-09-08 17:08 UTC
With the [#93185a5ee251c521025cb056bbb059fae47ac631](https://github.com/jocelynmallon/zshmarks/commit/93185a5ee251c521025cb056bbb059fae47ac631) commit, whenever zsh tries to parse the `zshmarks` plugin, it throws an error:

`zshmarks/zshmarks.plugin.zsh:129: parse error near ]]`

I removed this line since it's a safecheck to prevent `deletemark` on a non-existant mark (If I'm not mistaken) And I'm not too used to bash, so this works just fine for me.

**Comment by jocelynmallon** [comment] 2015-09-08 17:11
I can't reproduce this with my system.

What version of ZSH are you using? Are you using oh-my-zsh, antigen, prezto, or something else entirely?

**Comment by fernandofleury** [comment] 2015-09-08 18:43
![image](https://cloud.githubusercontent.com/assets/2780941/9744115/50af14fa-5640-11e5-83c3-e2c7dc9eae21.png)

Using `oh-my-zsh`.

**Comment by jocelynmallon** [comment] 2015-09-08 18:49
Can you try changing the line to single brackets and see if that works?

            if [ ! ${bookmark_array[(r)$bookmark_search]} ]; then

**Comment by fernandofleury** [comment] 2015-09-08 19:23
yes, working just fine.

**Comment by jocelynmallon** [comment] 2015-09-08 22:24
Ok, good to know, but still doesn't make any sense why that fixes it. Can you also try changing the line so the negation is outside the double braces:

    if ! [[ ${bookmark_array[(r)$bookmark_search]} ]] ; then

**Comment by fernandofleury** [comment] 2015-09-09 13:52
Sorry for the late response. And yeah, that fixes as well.

**Comment by jocelynmallon** [comment] 2015-09-09 16:34
Thanks for the help, pushed a fix, hopefully it works fine for everyone.

**Closed by jocelynmallon** 2015-09-09 16:34 UTC

**Comment by fernandofleury** [comment] 2015-09-09 17:06
Thanks for the quick response!

**Comment by mcallan83** [comment] 2015-09-11 03:38
Any chance this will get updated in the main repo? I am using this as a git submodule in my zsh setup.

**Comment by jocelynmallon** [comment] 2015-09-11 05:06
@mcallan83 this should have been fixed a couple of days ago in d177d0c62d5ef91d3034f3bcbfa42bbffbfafe89 have you updated your submodule recently?

**Comment by mcallan83** [comment] 2015-09-11 05:19
My bad! I thought I had, but I just updated and everything is working. Thanks for responding so quickly!
